# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_axf_mainshow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='axf_mainshow',
            table='axf_mainshow',
        ),
    ]
