# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20180109_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axf_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=100)),
                ('productimg', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('productlongname', models.CharField(max_length=100)),
                ('isxf', models.BooleanField()),
                ('pmdesc', models.CharField(max_length=100)),
                ('specifics', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('marketprice', models.CharField(max_length=100)),
                ('categoryid', models.CharField(max_length=100)),
                ('childcid', models.CharField(max_length=100)),
                ('childcidname', models.CharField(max_length=100)),
                ('dealerid', models.CharField(max_length=100)),
                ('storenums', models.CharField(max_length=100)),
                ('productnum', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
    ]
