# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20180109_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Axf_foodtypes',
        ),
    ]
