# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_axf_foodtypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Axf_foodtypes',
        ),
    ]
