# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_axf_foodtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_username', models.CharField(max_length=16, unique=True)),
                ('u_password', models.CharField(max_length=32)),
                ('u_sex', models.NullBooleanField(default=False)),
                ('u_phone', models.CharField(max_length=32)),
                ('u_email', models.CharField(max_length=32)),
                ('u_level', models.IntegerField(default=1)),
                ('u_icon', models.ImageField(upload_to='static/uploadfiles/icon')),
            ],
        ),
    ]
