# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_num', models.IntegerField(default=1)),
                ('cart_check', models.BooleanField(default=True)),
                ('cart_belong', models.BooleanField(default=False)),
                ('cart_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Axf_goods')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.TimeField(auto_now=True)),
                ('order_status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
    ]
